Vagrant.configure("2") do |config|
    #imagem base da box
    config.vm.box = "ubuntu/trusty64"

    #definindo o nome da box
    config.vm.define :agenda_config do |agenda_config|

        agenda_config.vm.hostname = "vagrant.puc.com"
        agenda_config.vm.provision "shell", path: "_vagrant/manifests/apt-get.sh"
        agenda_config.vm.provision "shell", path: "_vagrant/manifests/bootstrap.sh"
        agenda_config.vm.provision "shell", path: "_vagrant/manifests/mysql.sh"
        agenda_config.vm.provision "shell", path: "_vagrant/manifests/java.sh"
        agenda_config.vm.provision "shell", path: "_vagrant/manifests/maven.sh"

        agenda_config.vm.network "forwarded_port", guest: 3306, host: 3300, host_ip: "127.0.0.1"
        agenda_config.vm.network "forwarded_port", guest: 5000, host: 5000, host_ip: "127.0.0.1"

        #executando o puppet para instalar as dependencias
        agenda_config.vm.provision "puppet" do |puppet|
            puppet.manifests_path = "./_vagrant/manifests"
            puppet.manifest_file = "mysql.pp"
        end
        agenda_config.vm.provision "puppet" do |puppet|
                    puppet.manifests_path = "./_vagrant/manifests"
                    puppet.manifest_file = "agenda.pp"
        end

        agenda_config.vm.provision "shell", path: "_vagrant/manifests/agenda-service.sh", run: "always"

        config.vm.provider "virtualbox" do |virtualbox|
            virtualbox.customize [ "modifyvm", :id, "--cpus", "1" ]
            virtualbox.customize [ "modifyvm", :id, "--memory", "2048" ]
        end
    end
end