Vagrant.configure("2") do |config|
    #imagem base da box
    config.vm.box = "ubuntu/trusty64"

    #definindo o nome da box
    config.vm.define :doador_config do |doador_config|

        doador_config.vm.hostname = "vagrant.puc.com"
        doador_config.vm.provision "shell", path: "_vagrant/manifests/apt-get.sh"
        doador_config.vm.provision "shell", path: "_vagrant/manifests/bootstrap.sh"
        doador_config.vm.provision "shell", path: "_vagrant/manifests/mysql.sh"
        doador_config.vm.provision "shell", path: "_vagrant/manifests/java.sh"
        doador_config.vm.provision "shell", path: "_vagrant/manifests/maven.sh"

        doador_config.vm.network "forwarded_port", guest: 3306, host: 3301, host_ip: "127.0.0.1"
        doador_config.vm.network "forwarded_port", guest: 5001, host: 5001, host_ip: "127.0.0.1"

        #executando o puppet para instalar as dependencias
        doador_config.vm.provision "puppet" do |puppet|
            puppet.manifests_path = "./_vagrant/manifests"
            puppet.manifest_file = "mysql.pp"
        end
        doador_config.vm.provision "puppet" do |puppet|
                    puppet.manifests_path = "./_vagrant/manifests"
                    puppet.manifest_file = "doador-service.pp"
        end

        doador_config.vm.provision "shell", path: "_vagrant/manifests/doador-service.sh", run: "always"

        config.vm.provider "virtualbox" do |virtualbox|
            virtualbox.customize [ "modifyvm", :id, "--cpus", "1" ]
            virtualbox.customize [ "modifyvm", :id, "--memory", "1024" ]
        end
    end
end